---
title: "RStudio Instructor Training"
author: "Adithi R. Upadhya"
date: "22/02/2022"
output: html_document
---

```{r include = FALSE, message = FALSE, warning = FALSE}
# if tidyverse is not installed 
# install.packages("tidyverse")
# if already installed, load it here
library(tidyverse)
```

### Look at the first table band_members

```{r message = FALSE, warning = FALSE}
?band_members
glimpse(band_members)
```
### Look at the second table band_instruments

```{r message = FALSE, warning = FALSE}
glimpse(band_instruments) 
```

### Using dplyr, join tables band_members and band_instruments so that only the common observations in the both tables remain

```{r message = FALSE, warning = FALSE}
inner_join(band_instruments, band_members, by = "name") 
```


```{r message = FALSE, warning = FALSE}
inner_join(band_members, band_instruments, by = c("name" = "name")) 
```

### Now, using `left_join`, join band_instruments and band_members such that all the variables in band_instruments are retained

```{r message = FALSE, warning = FALSE, eval = FALSE}
left_join(---------, ---------, by = "name") 
```

### Solution

```{r message = FALSE, warning = FALSE}
left_join(band_instruments, band_members, by = "name") 
```